import { withOwner } from "@deliberation-ai/persistence";
import { revealCouncilControls } from "./workspace-navigation";
import { createServer } from "node:http";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import {expect, test, testOwnerId } from "./authenticated-test";
import { cancelDurableRun, closeDatabase, deleteProviderConnection, getDatabase } from "@deliberation-ai/persistence";
import { inArray } from "drizzle-orm";
import { runs } from "../../packages/persistence/src/schema";
import type { RunRecord } from "@deliberation-ai/application";
import type { ContinuationCompactionPacket, FrozenContinuation } from "@deliberation-ai/contracts";

test("reviews full history, starts a fresh council against a local mock and exports frozen provenance", async ({ page, request }) => withOwner(testOwnerId(), async () => {
  const sent: string[] = [];
  const server = createServer(async (incoming, outgoing) => {
    const chunks: Buffer[] = [];
    for await (const chunk of incoming) chunks.push(Buffer.from(chunk));
    const body = JSON.parse(Buffer.concat(chunks).toString("utf8")) as { messages: Array<{ role: string; content: string }> };
    sent.push(body.messages.find((message) => message.role === "user")!.content);
    const statement = sent.length === 2 ? "Azınlık önerisi: alternatif yaklaşım ayrıca incelensin." : `Bağımsız yerel öneri ${sent.length}`;
    const result = { summary: `Yerel yanıt ${sent.length}`, claims: [{ statement, quote: statement, kind: "recommendation" }] };
    outgoing.setHeader("content-type", "application/json");
    outgoing.end(JSON.stringify({ id: `offline-continuation-${sent.length}`, model: "offline-continuation", choices: [{ message: { content: JSON.stringify(result) } }], usage: { prompt_tokens: 9, completion_tokens: 6, total_tokens: 15 } }));
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("Fixture server unavailable");
  let connectionId: string | undefined;
  const ids: string[] = [];
  try {
    const saved = await request.post("/api/provider-connections", { data: { provider: "openai-compatible", label: `Offline continuation ${randomUUID()}`, apiKey: "", defaultModel: "offline-continuation", baseUrl: `http://127.0.0.1:${address.port}/v1`, endpointPreset: "litellm", reasoningProtocol: "none", structuredOutputMode: "json-object" } });
    expect(saved.ok()).toBe(true);
    connectionId = (await saved.json() as { id: string }).id;
    const members = ["member-a", "member-b"].map((id) => ({ id, label: id, role: "Analist", provider: "openai-compatible", connectionId, model: "offline-continuation", reasoningLevel: "default", webSearchMode: "off", councilRole: "analyst" }));
    const sourceResponse = await request.post("/api/runs", { data: { question: `Yerel devam akışı hangi görüşleri korur ${randomUUID()}?`, idempotencyKey: randomUUID(), providerMode: "remote", reviewRounds: 0, members } });
    expect(sourceResponse.status()).toBe(201);
    const sourceId = (await sourceResponse.json() as RunRecord).runId;
    ids.push(sourceId);
    await expect.poll(async () => (await (await request.get(`/api/runs/${sourceId}`)).json() as RunRecord).status, { timeout: 20_000 }).toBe("completed");
    const original = await (await request.get(`/api/runs/${sourceId}`)).json() as RunRecord;
    const context = await (await request.get(`/api/runs/${sourceId}/continuation`)).json() as FrozenContinuation;
    expect(sent).toHaveLength(2);
    await page.goto("/"); await revealCouncilControls(page);
    await page.locator(`[data-run-id="${sourceId}"]`).getByRole("button", { name: "Çalışmayı aç" }).click();
    await page.getByRole("button", { name: "Bu rapordan yeni soruyla devam et", exact: true }).click();
    const history = page.getByRole("region", { name: "Yeni çalışmanın geçmiş bağlamı" });
    await expect(history).toContainText(sourceId);
    await history.getByText("Gönderilecek geçmiş bağlamın tamamını incele", { exact: true }).click();
    await expect(history.locator("pre")).toContainText("Azınlık önerisi");
    for (const index of [1, 2]) await page.getByRole("combobox", { name: `Üye ${index} bağlantısı`, exact: true }).selectOption(connectionId);
    await page.getByRole("combobox", { name: "Çapraz inceleme turu", exact: true }).selectOption("0");
    const question = `Önceki görüşlere göre alternatifleri nasıl karşılaştırırız ${randomUUID()}?`;
    await page.getByLabel("Sorunuz", { exact: true }).fill(question);
    const start = page.getByRole("button", { name: "Konseyi çalıştır", exact: true });
    await expect(start).toBeDisabled();
    await page.getByLabel("Sorunuz", { exact: true }).press("Control+Enter");
    expect(sent).toHaveLength(2);
    await expect(page.getByRole("button", { name: "Duraklatılmış zamanlama oluştur", exact: true, includeHidden: true })).toBeDisabled();
    await history.getByRole("checkbox", { name: "Geçmiş bağlamı inceledim; yeni soruma dahil et" }).check();
    await expect(start).toBeEnabled();
    const posted = page.waitForResponse((response) => new URL(response.url()).pathname === "/api/runs" && response.request().method() === "POST");
    await start.click();
    const childResponse = await posted;
    expect(childResponse.status()).toBe(201);
    const childId = (await childResponse.json() as RunRecord).runId;
    ids.push(childId);
    await expect.poll(async () => (await (await request.get(`/api/runs/${childId}`)).json() as RunRecord).status, { timeout: 20_000 }).toBe("completed");
    expect(sent).toHaveLength(4);
    for (const text of sent.slice(2)) {
      const input = JSON.parse(text) as { question: string; continuationContext: FrozenContinuation; peers?: unknown };
      expect(input.question).toBe(question);
      expect(input.continuationContext).toEqual(context);
      expect(input.peers).toBeUndefined();
    }
    const child = await (await request.get(`/api/runs/${childId}`)).json() as RunRecord;
    expect(child.continuationContext).toEqual(context);
    expect(child.report!.memberResults.every((member) => !member.reusedFromRunId)).toBe(true);
    expect((await (await request.get(`/api/runs/${sourceId}`)).json() as RunRecord).report).toEqual(original.report);
    const exported = await (await request.post(`/api/runs/${childId}/export`)).json() as { continuationContext: FrozenContinuation };
    expect(exported.continuationContext).toEqual(context);
    const invalid = await request.post("/api/runs", { data: { question, idempotencyKey: randomUUID(), providerMode: "remote", reviewRounds: 0, members, continuationSource: { runId: sourceId, expectedSha256: "0".repeat(64) } } });
    expect(invalid.status()).toBe(409);
    expect(sent).toHaveLength(4);
    const branches = page.getByRole("region", { name: "Çalışma dalları", exact: true });
    await expect(branches).toContainText("Tam geçmişle devam");
    const draft = `Gezinirken korunacak soru taslağı ${randomUUID()}`;
    await page.getByLabel("Sorunuz", { exact: true }).fill(draft);
    await branches.locator(`[data-branch-run-id="${sourceId}"]`).getByRole("button", { name: "Bağlı çalışmayı aç" }).click();
    await expect(branches).toContainText("Bağımsız çalışma");
    await expect(page.getByLabel("Sorunuz", { exact: true })).toHaveValue(draft);
    await expect(history).toContainText(sourceId);
    await branches.locator(`[data-branch-run-id="${childId}"]`).getByRole("button", { name: "Bağlı çalışmayı aç" }).click();
    await expect(branches).toContainText("Tam geçmişle devam");
    await expect(page.getByLabel("Sorunuz", { exact: true })).toHaveValue(draft);
    expect(sent).toHaveLength(4);
    expect((await request.get(`/api/runs/${childId}/branches?childrenBefore=invalid`)).status()).toBe(400);
    expect((await request.get(`/api/runs/${randomUUID()}/branches`)).status()).toBe(404);
    const conversationPanel = page.getByRole("region", { name: "Konuşma kaydı", exact: true });
    await expect(conversationPanel).toContainText("2 çalışma");
    const conversationResponse = await request.get(`/api/runs/${childId}/conversation`);
    expect(conversationResponse.status()).toBe(200);
    const conversation = await conversationResponse.json() as { conversationId: string };
    const downloading = page.waitForResponse((response) => new URL(response.url()).pathname === `/api/conversations/${conversation.conversationId}/export`);
    const downloadedFile = page.waitForEvent("download");
    await conversationPanel.getByRole("button", { name: "Konuşmayı indir (JSON)", exact: true }).click();
    const downloadResponse = await downloading;
    expect(downloadResponse.status()).toBe(200);
    expect(downloadResponse.headers()["content-disposition"]).toContain(conversation.conversationId);
    const download = await downloadedFile;
    expect(download.suggestedFilename()).toBe(`deliberationai-conversation-${conversation.conversationId}.json`);
    const conversationExport = JSON.parse(await readFile((await download.path())!, "utf8")) as { schemaVersion: string; runs: Array<{ runId: string; payload: { continuationContext: FrozenContinuation | null } }> };
    expect(conversationExport.schemaVersion).toBe("deliberationai-conversation-export-v1");
    expect(conversationExport.runs.map((item) => item.runId).sort()).toEqual([sourceId, childId].sort());
    expect(conversationExport.runs.find((item) => item.runId === childId)?.payload.continuationContext).toEqual(context);
    const markdownDownload = page.waitForEvent("download");
    const markdownResponse = page.waitForResponse((response) => response.url().endsWith(`/api/conversations/${conversation.conversationId}/export?format=md`));
    await conversationPanel.getByRole("button", { name: "Konuşmayı indir (MD)", exact: true }).click();
    const mdResponse = await markdownResponse;
    expect(mdResponse.headers()["content-type"]).toBe("text/markdown; charset=utf-8");
    expect(mdResponse.headers()["cache-control"]).toBe("no-store");
    const mdFile = await markdownDownload;
    expect(mdFile.suggestedFilename()).toBe(`deliberationai-conversation-${conversation.conversationId}.md`);
    const mdText = await readFile((await mdFile.path())!, "utf8");
    for (const text of [sourceId, childId, "Azınlık önerisi", "# DeliberationAI konuşma geçmişi", "## Bağımsız ilk tur yanıtları", "continuationContext"]) expect(mdText).toContain(text);
    const synthesisDownload = page.waitForEvent("download");
    await page.getByRole("button", { name: "Sentezi indir (MD)", exact: true }).click();
    const synthesisFile = await synthesisDownload;
    expect(synthesisFile.suggestedFilename()).toBe(`deliberationai-synthesis-${childId}.md`);
    const synthesisText = await readFile((await synthesisFile.path())!, "utf8");
    expect(synthesisText).toContain("# DeliberationAI sentez kapsamı");
    expect(synthesisText).toContain(question);
    for (const label of ["### Dahil", "### Çözülmemiş", "### Dışarıda"]) expect(synthesisText).toContain(label);
    expect((await request.post(`/api/conversations/${conversation.conversationId}/export?format=md`, { headers: { origin: "https://foreign.example" } })).status()).toBe(403);
    expect((await request.post(`/api/runs/${childId}/export?format=md`, { headers: { origin: "https://foreign.example" } })).status()).toBe(403);
    expect((await request.post(`/api/runs/${randomUUID()}/export?format=md`)).status()).toBe(404);
    expect((await request.post(`/api/conversations/${randomUUID()}/export?format=md`)).status()).toBe(404);
    expect((await request.post(`/api/runs/${childId}/export?format=html`)).status()).toBe(400);
    expect((await request.post(`/api/conversations/${conversation.conversationId}/export?format=html`)).status()).toBe(400);
    expect((await request.post(`/api/conversations/${conversation.conversationId}/export`, { headers: { origin: "https://foreign.example" } })).status()).toBe(403);
    expect((await request.post(`/api/conversations/${randomUUID()}/export`)).status()).toBe(404);
    await expect(page.getByLabel("Sorunuz", { exact: true })).toHaveValue(draft);
    expect(sent).toHaveLength(4);
    await history.getByRole("button", { name: "Geçmiş bağlamı kaldır", exact: true }).click();
    await expect(history).toHaveCount(0);
  } finally {
    for (const id of ids) await cancelDurableRun(id);
    if (ids.length) await getDatabase().delete(runs).where(inArray(runs.id, ids));
    if (connectionId) {
      await deleteProviderConnection(connectionId);
    }
    await closeDatabase();
    await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
  }
}));

test("reviews a manual summary and omissions, invalidates approval on edits and keeps original text out of local provider calls", async ({ page, request }) => withOwner(testOwnerId(), async () => {
  const sent: string[] = [];
  const server = createServer(async (incoming, outgoing) => {
    const chunks: Buffer[] = [];
    for await (const chunk of incoming) chunks.push(Buffer.from(chunk));
    const body = JSON.parse(Buffer.concat(chunks).toString("utf8")) as { messages: Array<{ role: string; content: string }> };
    sent.push(body.messages.find((message) => message.role === "user")!.content);
    const statement = sent.length <= 2 ? "PRIVATE_RAW_ALTERNATIVE: ayrı bir yol incelensin." : "Yeni bağımsız yerel değerlendirme.";
    outgoing.setHeader("content-type", "application/json");
    outgoing.end(JSON.stringify({ id: `offline-compact-${sent.length}`, model: "offline-compact", choices: [{ message: { content: JSON.stringify({ summary: `Özet ${sent.length}`, claims: [{ statement, quote: statement, kind: "recommendation" }] }) } }], usage: { prompt_tokens: 9, completion_tokens: 6, total_tokens: 15 } }));
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("Fixture server unavailable");
  let connectionId: string | undefined;
  const ids: string[] = [];
  try {
    const saved = await request.post("/api/provider-connections", { data: { provider: "openai-compatible", label: `Offline compact ${randomUUID()}`, apiKey: "", defaultModel: "offline-compact", baseUrl: `http://127.0.0.1:${address.port}/v1`, endpointPreset: "litellm", reasoningProtocol: "none", structuredOutputMode: "json-object" } });
    expect(saved.ok()).toBe(true);
    connectionId = (await saved.json() as { id: string }).id;
    const members = ["member-a", "member-b"].map((id) => ({ id, label: id, role: "Analist", provider: "openai-compatible", connectionId, model: "offline-compact", reasoningLevel: "default", webSearchMode: "off", councilRole: "analyst" }));
    const sourceResponse = await request.post("/api/runs", { data: { question: `Yerel kısaltma hangi bilgiyi korur ${randomUUID()}?`, idempotencyKey: randomUUID(), providerMode: "remote", reviewRounds: 0, members } });
    expect(sourceResponse.status()).toBe(201);
    const sourceId = (await sourceResponse.json() as RunRecord).runId;
    ids.push(sourceId);
    await expect.poll(async () => (await (await request.get(`/api/runs/${sourceId}`)).json() as RunRecord).status, { timeout: 20_000 }).toBe("completed");
    const original = await (await request.get(`/api/runs/${sourceId}`)).json() as RunRecord;
    const packetResponse = await request.get(`/api/runs/${sourceId}/continuation?mode=compaction`);
    expect(packetResponse.ok()).toBe(true);
    const packet = await packetResponse.json() as ContinuationCompactionPacket;
    await page.goto("/"); await revealCouncilControls(page);
    await page.locator(`[data-run-id="${sourceId}"]`).getByRole("button", { name: "Çalışmayı aç" }).click();
    await page.getByRole("button", { name: "Geçmişi kısaltarak yeni soruyla devam et", exact: true }).click();
    const editor = page.getByRole("region", { name: "Geçmişi elle kısaltma", exact: true });
    await expect(editor).toContainText("Raporun tamamı");
    await editor.getByText("Özgün geçmişi ve çıkarılan ayrıntıları incele", { exact: true }).click();
    await expect(editor.locator("pre")).toContainText("PRIVATE_RAW_ALTERNATIVE");
    const summary = editor.getByLabel("Yeni çalışmaya gönderilecek geçmiş özeti", { exact: true });
    await summary.fill("Alternatif yol ve belirsizlikler bir sonraki değerlendirmede ayrıca incelensin.");
    const approval = editor.getByRole("checkbox", { name: "Özeti ve atlanan bilgileri inceledim; bu kısaltmayla devam et", exact: true });
    for (const index of [1, 2]) await page.getByRole("combobox", { name: `Üye ${index} bağlantısı`, exact: true }).selectOption(connectionId);
    await page.getByRole("combobox", { name: "Çapraz inceleme turu", exact: true }).selectOption("0");
    const question = `Bu özete göre hangi varsayımları inceleyelim ${randomUUID()}?`;
    await page.getByLabel("Sorunuz", { exact: true }).fill(question);
    const start = page.getByRole("button", { name: "Konseyi çalıştır", exact: true });
    await expect(start).toBeDisabled();
    await page.getByLabel("Sorunuz", { exact: true }).press("Control+Enter");
    expect(sent).toHaveLength(2);
    await approval.check();
    await expect(start).toBeEnabled();
    await summary.fill("Düzenlenmiş özet: alternatif yol ve açık belirsizlikler ayrıca incelensin.");
    await expect(approval).not.toBeChecked();
    await expect(start).toBeDisabled();
    await expect(page.getByRole("button", { name: "Duraklatılmış zamanlama oluştur", exact: true, includeHidden: true })).toBeDisabled();
    await approval.check();
    await expect(start).toBeEnabled();
    const submitted = page.waitForResponse((response) => new URL(response.url()).pathname === "/api/runs" && response.request().method() === "POST");
    await start.click();
    const childResponse = await submitted;
    expect(childResponse.status()).toBe(201);
    const childId = (await childResponse.json() as RunRecord).runId;
    ids.push(childId);
    await expect.poll(async () => (await (await request.get(`/api/runs/${childId}`)).json() as RunRecord).status, { timeout: 20_000 }).toBe("completed");
    expect(sent).toHaveLength(4);
    for (const actual of sent.slice(2)) {
      expect(actual).toContain("Düzenlenmiş özet");
      expect(actual).not.toContain("PRIVATE_RAW_ALTERNATIVE");
      expect(actual).not.toContain("originalContent");
      expect(actual).toContain("tam rapor değildir");
    }
    const child = await (await request.get(`/api/runs/${childId}`)).json() as RunRecord;
    expect(child.continuationArchive!.packet).toEqual(packet);
    expect(child.continuationArchive!.selection.summary).toContain("Düzenlenmiş özet");
    expect(child.continuationContext!.version).toBe("run-continuation-v2");
    const exported = await (await request.post(`/api/runs/${childId}/export`)).json() as RunRecord;
    expect(exported.continuationArchive).toEqual(child.continuationArchive);
    expect(exported.continuationArchive!.packet.originalContent).toContain("PRIVATE_RAW_ALTERNATIVE");
    expect((await (await request.get(`/api/runs/${sourceId}`)).json() as RunRecord).report).toEqual(original.report);
    const denied = await request.post("/api/runs", { data: { question, idempotencyKey: randomUUID(), providerMode: "remote", reviewRounds: 0, members, continuationSource: { runId: sourceId, expectedSha256: packet.sourceSha256, compaction: { version: "manual-continuation-compaction-v1", summary: "A forged unreviewed summary", reviewed: false } } } });
    expect(denied.status()).toBe(422);
    expect(sent).toHaveLength(4);
  } finally {
    for (const id of ids) await cancelDurableRun(id);
    if (ids.length) await getDatabase().delete(runs).where(inArray(runs.id, ids));
    if (connectionId) await deleteProviderConnection(connectionId);
    await closeDatabase();
    await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
  }
}));
